### ISSUE TITLE
R 4.2.0: using first element strikes again

### ISSUE THREAD

**Issue by dmenne** [rstudio/thematic#122] opened 2022-04-29 15:46 UTC
Using your example: 

https://rstudio.github.io/thematic/index.html

Related context: 

https://github.com/rstudio/shiny/issues/3626
https://github.com/rstudio/shiny/pull/3625

``` 
> shiny::runApp()
Lade nötiges Paket: shiny

Listening on http://127.0.0.1:6175
 [100%] Downloaded 109448 bytes...
Fontconfig error: Cannot load default config file
Warning in check_font_path(italic, "italic") :
  'italic' should be a length-one vector, using the first element
Warning in check_font_path(italic, "italic") :
  'italic' should be a length-one vector, using the first element

**Comment by cpsievert** [comment] 2022-04-29 17:35
Duplicate of #120

**Closed by cpsievert** 2022-04-29 17:35 UTC
